[package]
name = "SshScript"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.127"
chrono = "0.4.38"
rand = "0.8.5"
rusqlite = { version = "0.32.1"}
