[package]
name = "CheckUser"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.127"
rusqlite = { version = "0.32.1" }
chrono = "0.4.38"
